### ISSUE TITLE
InstitutionsEndpoint.GetInstitutions - US is not a valid choice?

### ISSUE THREAD

**Issue by JonathanHart-CIS** [RobinTTY/NordigenApiClient#5]
Hi - if I call the GetInstitutions with Country = US I get an error below.

according to this page https://bankaccountdata.gocardless.com/api/docs#/institutions/retrieve%20all%20supported%20Institutions%20in%20a%20given%20country United States of America should be country code US.

System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Deserialization failed, please report this issue to the library author: https://github.com/RobinTTY/NordigenApiClient/issues
The following JSON content caused the problem: {"country":{"summary":"Invalid country choice.","detail":"US is not a valid choice."},"status_code":400}
  Source=RobinTTY.NordigenApiClient
  StackTrace:
   at RobinTTY.NordigenApiClient.Models.Responses.NordigenApiResponse`2.<FromHttpResponse>d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at RobinTTY.NordigenApiClient.NordigenClient.<MakeRequest>d__26`2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RobinTTY.NordigenApiClient.Endpoints.InstitutionsEndpoint.<GetInstitutions>d__2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

  This exception was originally thrown at this call stack:
    System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(System.Type)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

Inner Exception 1:
JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[System.String]. Path: $.country | LineNumber: 0 | BytePositionInLine: 12.

**Comment by RobinTTY** [comment]
I'll fix the deserialization issue soon though.

**Comment by JonathanHart-CIS** [comment]
ah - that is just confusing documentation - as the page I first linked to has a drop down country list - and at the bottom there is United Status with code US!  never mind ;)
